AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS application stack in ap-southeast-4:
  S3, KMS, DynamoDB, EventBridge for shared infrastructure.

Parameters:
  TableName:
    Type: String
    Default: OrdersTable

Resources:
  # Encryption key
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      Description: CMK for all at-rest encryption

  # Static assets bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-static-assets"
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # DynamoDB
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk, AttributeType: S }
        - { AttributeName: sk, AttributeType: S }
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref KMSKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # EventBridge bus
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "${AWS::StackName}-bus"

Outputs:
  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref DynamoDBTable
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDBTable"

  EventBusName:
    Description: EventBridge bus name
    Value: !Ref EventBus
    Export:
      Name: !Sub "${AWS::StackName}-EventBus"

  S3BucketName:
    Description: S3 bucket name
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-S3Bucket"

  KMSKeyId:
    Description: KMS key ID
    Value: !Ref KMSKey
    Export:
      Name: !Sub "${AWS::StackName}-KMSKey"
