AWSTemplateFormatVersion: "2010-09-09"
Description: Global WAFv2 WebACL for CloudFront

Parameters:
  WebAclName:
    Type: String
    Default: HighScalableWebACL
  GitHubSha:
    Type: String
    Description: GitHub commit SHA to make the WebACL name unique
    Default: latest

Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${WebAclName}-${AWS::Region}-${GitHubSha}"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${WebAclName}-${AWS::Region}-${GitHubSha}-metrics"
      Rules: [] # add your rules here

Outputs:
  WebACLArn:
    Value: !GetAtt WebACL.Arn
    Export:
      Name: !Sub "GlobalWebACLArn-${GitHubSha}"
